import { BookOpen, CheckSquare, ClipboardList, Flag, FolderKanban, Layers3, Library, NotebookPen, Route, Target, TimerReset } from "lucide-react";

export const featureConfig = {
  notes: { title: "Notes", description: "Capture ideas, references, and useful explanations.", eyebrow: "Knowledge base", icon: NotebookPen, fields: [{ name: "title", label: "Title" }, { name: "content", label: "Content", type: "textarea", wide: true }, { name: "tags", label: "Tags", type: "tags" }, { name: "pinned", label: "Pin this note", type: "checkbox" }] },
  roadmaps: { title: "Roadmaps", description: "Turn ambitious learning outcomes into visible steps.", eyebrow: "Learning paths", icon: Route, fields: [{ name: "title", label: "Title" }, { name: "description", label: "Description", type: "textarea", wide: true }] },
  checklists: { title: "Checklists", description: "Keep repeatable preparation and quality checks reliable.", eyebrow: "Repeatable systems", icon: CheckSquare, fields: [{ name: "title", label: "Title" }] },
  topics: { title: "Topics to Learn", description: "Move your learning backlog from curiosity to mastery.", eyebrow: "Learning board", icon: Layers3, board: true, fields: [{ name: "title", label: "Title" }, { name: "description", label: "Description", type: "textarea", wide: true }, { name: "status", label: "Status", type: "select", options: ["Not Started", "Learning", "Mastered"] }, { name: "priority", label: "Priority", type: "select", options: ["Low", "Medium", "High"] }, { name: "tags", label: "Tags", type: "tags" }] },
  remember: { title: "Questions to Remember", description: "Use active recall to keep important ideas within reach.", eyebrow: "Flashcards", icon: BookOpen, flashcards: true, fields: [{ name: "question", label: "Question" }, { name: "answer", label: "Answer", type: "textarea", wide: true }, { name: "tags", label: "Tags", type: "tags" }, { name: "confidence", label: "Confidence", type: "number" }] },
  diary: { title: "Diary", description: "Notice what worked and tell the story of your learning.", eyebrow: "Reflection", icon: NotebookPen, fields: [{ name: "title", label: "Title" }, { name: "entryDate", label: "Date", type: "date" }, { name: "mood", label: "Mood" }, { name: "content", label: "Reflection", type: "textarea", wide: true }] },
  tasks: { title: "Tasks", description: "Keep the next useful action clear and manageable.", eyebrow: "Action list", icon: ClipboardList, filters: true, fields: [{ name: "title", label: "Title" }, { name: "dueDate", label: "Due date", type: "date" }, { name: "description", label: "Description", type: "textarea", wide: true }, { name: "status", label: "Status", type: "select", options: ["Pending", "In Progress", "Completed", "Blocked"] }, { name: "priority", label: "Priority", type: "select", options: ["Low", "Medium", "High"] }, { name: "tags", label: "Tags", type: "tags" }] },
  goals: { title: "Progress", description: "Measure steady movement toward meaningful outcomes.", eyebrow: "Goals", icon: Target, fields: [{ name: "title", label: "Title" }, { name: "deadline", label: "Target date", type: "date" }, { name: "current", label: "Current", type: "number" }, { name: "target", label: "Target", type: "number" }, { name: "unit", label: "Unit" }] },
  "custom-modules": { title: "Custom Modules", description: "Create a flexible home for learning that does not fit elsewhere.", eyebrow: "Flexible workspace", icon: FolderKanban, schema: "customModules", fields: [{ name: "name", label: "Module name" }] },
  resources: { title: "Resources", description: "Save valuable material and return to it with intention.", eyebrow: "Learning library", icon: Library, fields: [{ name: "title", label: "Title" }, { name: "url", label: "URL", type: "url" }, { name: "type", label: "Type", type: "select", options: ["Article", "Video", "Course", "Book", "Documentation", "Other"] }, { name: "topic", label: "Topic" }, { name: "tags", label: "Tags", type: "tags" }, { name: "completed", label: "Completed", type: "checkbox" }] },
  "study-sessions": { title: "Study Sessions", description: "Plan focused blocks and build a record of deliberate practice.", eyebrow: "Focus history", icon: TimerReset, schema: "studySessions", fields: [{ name: "title", label: "Session title" }, { name: "topic", label: "Topic" }, { name: "plannedDate", label: "Planned date", type: "date" }, { name: "duration", label: "Minutes", type: "number" }, { name: "status", label: "Status", type: "select", options: ["Planned", "Completed", "Skipped"] }, { name: "notes", label: "Notes", type: "textarea", wide: true }] }
};

export const navGroups = [
  { label: "Overview", items: [["/", "Dashboard", Layers3], ["/focus", "Focus Timer", TimerReset]] },
  { label: "Organize", items: [["/notes", "Notes", NotebookPen], ["/roadmaps", "Roadmaps", Route], ["/checklists", "Checklists", CheckSquare], ["/topics", "Topics to Learn", Layers3], ["/tasks", "Tasks", ClipboardList], ["/goals", "Progress", Flag]] },
  { label: "Learn", items: [["/remember", "Questions to Remember", BookOpen], ["/resources", "Resources", Library], ["/study-sessions", "Study Sessions", TimerReset], ["/diary", "Diary", NotebookPen], ["/custom-modules", "Custom Modules", FolderKanban]] }
];
